micronaut:
  application:
    name: outerjoin
datasources:
  default:
    url: 'jdbc:tc:postgresql:13:///test'
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    dialect: POSTGRES
    schema-generate: CREATE_DROP
